server:
  port: 9003

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/db-demo"
    username: "root"
    password: "Gold1Silver2"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: none