spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://db-mysql/db-demo"
    username: "root"
    password: "Gold1Silver2"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
  platform: mysql

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://authenticationservice:9999/uaa/oauth/token_key
