spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/micro-organization"
    username: "root"
    password: "12345"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
