example.property: "I AM IN THE DEFAULT at sub folder! - dev "

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://172.18.0.1:9999/uaa/oauth/token_key

redis:
  server: "redis"
  port: "6379"
