example.property: "I AM IN THE DEFAULT at sub folder -- prod yml"

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://database:3306/emall"
    username: "root"
    password: "Gold1Silver2"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: none

redis:
  server: "redis"
  port: "6379"
