example.property: "I AM IN THE DEFAULT sub folder - test "

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://db-mysql/db-demo"
    username: "root"
    password: "Gold1Silver2"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
  platform: mysql
    
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://authenticationservice/uaa/oauth/token_key
redis:
  server: "redis"
  port: "6379"
